name: flutter_challenge_202106
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # internationalization and string formatter
  intl: 0.17.0

  # Google fonts
  google_fonts: 2.3.1

  # Bloc
  bloc: 8.0.3
  flutter_bloc: 8.0.1
  
  # Firebase
  firebase_core: 1.13.1
  cloud_firestore: 3.1.10

  # Rating Bar
  flutter_rating_bar: 4.0.0

  # Currency Price Formatter
  currency_text_input_formatter: 2.1.5

dependency_overrides:
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/